version: '3'

services:

  db:
    build:
      context: .
    image: mysql:5.7
    platform: linux/x86_64/v8
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network    

  node:
    build:
      context: ./node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 docker-entrypoint.sh
    command: node index.js
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node-network  

    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx   
    restart: always 
    networks:
      - node-network
    ports:
      - '8080:80'
    depends_on:
      - node

networks:
  node-network:
    driver: bridge
